version: "3.9"
services:
  app:
    image: docker_rails
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    ports:
      - 3000:3000
  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: postgres